include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_use_package_imports: true
    always_put_required_named_parameters_first: true
    cascade_invocations: true
    eol_at_end_of_file: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_parameters: true
    require_trailing_commas: true
    lines_longer_than_80_chars: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
